spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pubg_tournaments
    username: root
    password: Viratkohli@18
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089
